### ISSUE TITLE
 System Landscape icon request

### ISSUE THREAD

**Issue by LiquidKoala** [hycomsa/hycom-c4#2]
Thanks for an excellent plug-in, I'm using it frequently. Please consider adding a System Landscape icon https://c4model.com/#SystemLandscapeDiagram ?

**Comment by maciek365** [comment]
Hi,
I'm very happy you like it!

I will consider your request, but I'm not sure what do you exactly requesting for.
What do you mean by "System Landscape icon"?
Do you mean adding a new dedicated diagram title element (like e.g. Containers diagram title or Components diagram title)?

Please give me some more information about it.
