### ISSUE TITLE
Cannot delete legend from diagram

### ISSUE THREAD

**Issue by rmaidment** [hycomsa/hycom-c4#3]
Hello
I find that if I add the legend to a diagram, I cannot delete it!
I am using the desktop version of diagrams.net, version 15.5.6.  I add the legend by opening the .xml file as a library, and then drag the legend onto my diagram.  If I select the legend on my diagram, I can move it, but the delete key does nothing and the Delete option in the main Edit menu is greyed out.  If I right-click the legend, the context menu does not include a delete option.

**Comment by maciek365** [comment]
Thank you for using Hycom C4 for diagrams.net
I've fixed this problem a few minutes ago.
Please use the newest version of the Hycom C4 library and enjoy creating C4 diagrams :-)
